version: '3.8'

services:
  redis:
    image: redis:7.4-alpine
    container_name: live-platform-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - live-platform-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  redisinsight:
    image: redis/redisinsight:2.66.0
    container_name: live-platform-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    depends_on:
      - redis
    networks:
      - live-platform-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: live-mysql
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog-row-image=FULL
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=live
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-1234}
    networks:
      - live-platform-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/master/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  mongodb:
    image: mongo:7
    container_name: live-platform-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - live-platform-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
  redis_data:
  es-data:
  mongodb_data:
  redisinsight-data:

networks:
  live-platform-network:
    driver: bridge
    name: live-platform-network
