server:
  port: 8090
  servlet:
    session:
      timeout: 1d

spring:
  profiles:
    default: local
  servlet:
    encoding:
      charset: UTF-8
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-5.2

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
  packages-to-scan: org.giglab.live.commerce.api.controller